// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFqp4mt9i3XNfKSTiCmgunnTW1rMAJyf8',
    appId: '1:534725597570:web:7fff7b635f8395857cd79b',
    messagingSenderId: '534725597570',
    projectId: 'thandridb',
    authDomain: 'thandridb.firebaseapp.com',
    storageBucket: 'thandridb.appspot.com',
    measurementId: 'G-7CQJQE7CK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VuF-J4EMRFjTWml8AcoeTLZCZYy01Yk',
    appId: '1:534725597570:android:e6a30df2ef317fde7cd79b',
    messagingSenderId: '534725597570',
    projectId: 'thandridb',
    storageBucket: 'thandridb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoB1265jiHkivdA83aCe-nCAubFTnJX4',
    appId: '1:534725597570:ios:713c6691c3ff3db47cd79b',
    messagingSenderId: '534725597570',
    projectId: 'thandridb',
    storageBucket: 'thandridb.appspot.com',
    iosBundleId: 'com.example.thandriSannidhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoB1265jiHkivdA83aCe-nCAubFTnJX4',
    appId: '1:534725597570:ios:888ff328089b45697cd79b',
    messagingSenderId: '534725597570',
    projectId: 'thandridb',
    storageBucket: 'thandridb.appspot.com',
    iosBundleId: 'com.example.thandriSannidhi.RunnerTests',
  );
}
